# Generated by Django 3.0.7 on 2020-07-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Жанр книги',
                'verbose_name_plural': 'Жанры книг',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductGenre'),
        ),
    ]
