# Generated by Django 3.0.7 on 2020-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200703_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
